[package]
name = "noteap-client"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
colored = "3.0.0"
dirs = "6.0.0"
notify-rust = "4.11.7"
reqwest = "0.12.20"
serde_json = "1.0.140"
tokio = {version = "1.21.2", features = ["full"]}
